<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="ssimha1M-BNG1" failures="2" tests="2" name="Default test(failed)" time="0.067" errors="0" timestamp="2024-06-28T09:10:11 IST">
  <testcase classname="day25.Demo9" name="deleteProduct" time="0.018">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at day25.Demo9.deleteProduct(Demo9.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- deleteProduct -->
  <testcase classname="day25.Demo9" name="deleteUser" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at day25.Demo9.deleteUser(Demo9.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser -->
  <testcase classname="day25.Demo9" name="createUser" time="0.0">
    <ignored/>
  </testcase> <!-- createUser -->
  <testcase classname="day25.Demo9" name="createProduct" time="0.0">
    <ignored/>
  </testcase> <!-- createProduct -->
</testsuite> <!-- Default test(failed) -->
